second project/bots/urls.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls import path

from .views import *

app_name = 'bots'

urlpatterns = [
    path('setwebhook/', bot_setwebhook, name='bot_setwebhook'),
    path('unsetwebhook/', bot_unsetwebhook, name='bot_unsetwebhook'),
    path('incoming/<token>/telegram', csrf_exempt(ViewTelegramBot.as_view()), name="incoming_telegram"),
    path('incoming/viber', csrf_exempt(ViewViberBot.as_view()), name="incoming_viber"),
    path('incoming/vk', csrf_exempt(ViewVKBot.as_view()), name="incoming_vk"),
    path('incoming/fb', csrf_exempt(ViewFBBot.as_view()), name="incoming_fb"),
]

second project/config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import HomeView, DashboardView

#from rest_framework_swagger.views import get_swagger_view

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

#schema_view = get_swagger_view(title='API Grain Club')

schema_view = get_schema_view(
   openapi.Info(
      title="API Grain Club",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/bots/', include('bots.urls_api')),
    path('api/', include('billing.urls_api')),
    path('api/o/', include('core.urls_api_oauth2')),
    path('api/', include('core.urls_api')),
    path('api/hooks/', include('hooks.urls_api_hooks')),
    path('api/', include('payments.urls_api_tariffs')),
    path('api/orders/', include('billing.urls_api_orders')),
    path('api/payments/', include('payments.urls_api')),
    path('api/catalog/video/', include('video_catalog.urls_api')),
#    path('api/v1/', schema_view),

    path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/v1/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('bots/', include('bots.urls')),
    path('oauth2/',
         include('oauth2_provider.urls', namespace='oauth2_provider')),


]

urlpatterns += i18n_patterns(

    path('', HomeView.as_view(), name="home"),
    path('', include('core.urls_auth')),
    path('chat/', include('chat.urls')),
    path('dashboard', DashboardView.as_view(), name="dashboard"),
    path('events/', include('events.urls')),
    path('api/', include('events.urls_api')),
    path('api/', include('marketing.urls_api')),
    path('api/', include('core.urls_api_i18n')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

second project/events/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *

app_name = 'events'

urlpatterns = [
    path('', login_required(ListEvents.as_view()),
         name="home"),
    path('create/', login_required(CreateEvent.as_view()),
         name='create'),
    path('<pk>/update', login_required(UpdateEvent.as_view()),
         name='update'),
    path('<pk>/remove', login_required(DeleteEvent.as_view()),
         name='remove'),

    path('<event>/units/create/', login_required(CreateUnit.as_view()),
         name='create-unit'),
    path('<event>/units/<pk>', login_required(DetailUnit.as_view()),
         name='detail-unit'),
    path('<event>/units/<pk>/update', login_required(UpdateUnit.as_view()),
         name='update-unit'),
    path('units/<pk>/remove', login_required(DeleteUnit.as_view()),
         name='remove-unit'),

    path('<event>/units/<unit>/lessons/create/',
         login_required(CreateLesson.as_view()), name='create-lesson'),
    path('<event>/units/<unit>/lessons/<pk>',
         login_required(DetailLesson.as_view()), name='detail-lesson'),
    path('<event>/units/<unit>/lessons/<pk>/update',
         login_required(UpdateLesson.as_view()), name='update-lesson'),
    path('lessons/<pk>/remove',
         login_required(DeleteLesson.as_view()), name='remove-lesson'),

    path('<event>/units/<unit>/webinars/create/',
         login_required(CreateWebinar.as_view()), name='create-webinar'),
    path('<event>/units/<unit>/webinars/<pk>/update',
         login_required(UpdateWebinar.as_view()), name='update-webinar'),
    path('<event>/units/<unit>/webinars/<pk>',
         login_required(DetailWebinar.as_view()), name='detail-webinar'),
    path('webinars/<pk>/remove',
         login_required(DeleteWebinar.as_view()), name='remove-webinar'),

    path('<event>/add_all_users', login_required(add_all_user_to_event),
         name="add_all_user_to_event"),

    path('<pk>', login_required(DetailEvent.as_view()),
         name="event-detail"),
    #path('subscribe', SignupView.as_view(), name="signup"),
]

second project/events/models/abstract_models.py
from django.db import models

from core.models import AbstractNotRemoveModel, AbstractModelWithTitle, VideoMixin
from .image_storages import ImageStorage


class AbstractWithDescription(models.Model):
    description = models.TextField(
        blank=True, null=True, verbose_name='Описание')
    summary = models.TextField(
        blank=True, null=True, verbose_name='Краткое описание')
    image_storage = models.ForeignKey(
        ImageStorage, on_delete=models.CASCADE, verbose_name='Хранилище изображения',
         blank=True, null=True,)

    class Meta:
        abstract = True

    @property
    def image(self):
        return self.image_storage.image

    def attach_image(self, value, user):
        image_storage, _ = ImageStorage.objects.get_or_create(
            user=user, image=value)
        self.image_storage = image_storage

    @property
    def cover(self):
        return self.image_storage.cover

second project/events/models/cartificate_type_lesson_elements.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from .abstract_models import AbstractNotRemoveModel
from .lesson_elements import LessonElement


class CertificateTypeLessonElement(AbstractNotRemoveModel):
    """
    Модель типа сертификат элементов урока.
    """
    lesson_element = models.OneToOneField(
        LessonElement, on_delete=models.CASCADE,
        related_name='certificate', verbose_name='Сертификат',
        blank=True, null=True)
    title = models.CharField('Название', max_length=254)
    signature = models.CharField('Подпись', max_length=254)
    date_expiration = models.DateField('Дата окончания курса',
                                       blank=True, null=True)

    class Meta:
        verbose_name = 'Тип сертификат - элемента урока'
        verbose_name_plural = 'Тип сертификат - элементов уроков'

    def is_expiration(self):
        return self.date_expiration is not None


@receiver(post_save, sender=LessonElement)
def lesson_post_save(sender, instance, **kwargs):
    if instance.is_certificate:
        CertificateTypeLessonElement\
            .objects.\
            get_or_create(
                lesson_element=instance,
                defaults={
                    'title': instance.lesson.unit.event.title,
                    'signature': instance.lesson.unit.event.owner.school.title
                }
            )

second project/events/models/chat_messages.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from .webinars import Webinar


class Message(models.Model):
    webinar = models.ForeignKey(
        Webinar, on_delete=models.CASCADE,
        related_name='messages', verbose_name='Сообщение в чате')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='chat_messages', verbose_name='Автор')
    body = models.CharField(
        max_length=254, blank=False, null=False, verbose_name='Тело сообщения')
    pub_date = models.DateTimeField('Дата сообщения', default=timezone.now)

second project/events/models/check_list_type_lesson_elements.py
from datetime import time

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


from .abstract_models import AbstractNotRemoveModel
from .lesson_elements import LessonElement


class CheckListTypeLessonElement(AbstractNotRemoveModel):
    """
    Модель содержащая домашнее задание к соответсвующиему типу урока
    """
    lesson_element = models.OneToOneField(
        LessonElement, on_delete=models.CASCADE,
        related_name='check_list', verbose_name='элемент урока',
        blank=True, null=True)
    class Meta:
        verbose_name = 'Тип чек лист- элемента урока'
        verbose_name_plural = 'Тип чек лист - элементов уроков'


class CheckListElement(AbstractNotRemoveModel):
    parent = models.ForeignKey(
        CheckListTypeLessonElement, on_delete=models.CASCADE,
        related_name='elements', blank=True, null=True)
    title = models.CharField('Заголовок', max_length=200,
        blank=True, null=True)
    url = models.URLField('Ссылка на видео')
    body = models.TextField('Задание', blank=True, null=True)
    order = models.PositiveSmallIntegerField(
        default=0, blank=False, null=False, verbose_name='Вес', unique=True)


@receiver(post_save, sender=LessonElement)
def lesson_post_save(sender, instance, **kwargs):
    if instance.is_check_list:
        CheckListTypeLessonElement.objects.get_or_create(lesson_element=instance)

second project/events/models/events.py
import decimal
from django.contrib.auth.models import User
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey
from jsonfield import JSONField
from .abstract_models import (
    AbstractNotRemoveModel, AbstractModelWithTitle, AbstractWithDescription)


class CategoryEvent(AbstractNotRemoveModel, MPTTModel,
                    AbstractModelWithTitle, AbstractWithDescription):
    """Категории курсов"""
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = 'Категория курса'
        verbose_name_plural = 'Категория курсов'

    class MPTTMeta:
        order_insertion_by = ['title']


class Event(AbstractModelWithTitle,
            AbstractWithDescription, AbstractNotRemoveModel):
    GS_YES_NO, GS_POINT = range(2)
    CHOICES_GRADING_SYSTEM_TYPES =(
        (GS_YES_NO, 'сдал/не сдал'),
        (GS_POINT, 'балльная система оценивания')
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='owner_events', verbose_name='Владелец курса')
    participants = models.ManyToManyField(
        User, related_name='events', verbose_name='Участники курса')
    category = models.ForeignKey(
        CategoryEvent, on_delete=models.PROTECT, null=True, blank=True,
        related_name='events', verbose_name='категория')
    published = models.BooleanField('Флаг публикации', default=False)
    open_all_unit = models.BooleanField(
        'Флаг открытости блоков', default=False)
    grading_system = models.PositiveSmallIntegerField(
        '', choices=CHOICES_GRADING_SYSTEM_TYPES,
        default=GS_POINT)
    default_grade_completed_lesson = models.PositiveSmallIntegerField(
        'Оценка по умолчанию пройденого урока', default=0)
    fixed_date_begin = models.BooleanField(
        'Флаг фиксированной даты начала', default=False)
    date_begin = models.DateTimeField(
        'Дата начала', blank=True, null=True)
    domain_name = models.CharField(
        max_length=255, blank=True, verbose_name='Доменное имя', null=True)
    has_units = models.BooleanField('Флаг блочности курса', default=False)
    meta = JSONField('Meta', blank=True, null=True)
    paid = models.BooleanField('Платный/Бесплатный', default=True)

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    def student_is_attach(self, student):
        return student in self.participants.all()

    @property
    def payment(self):
        return False

    @property
    def percent_completion(self):
        return 0

    def __init__(self, *args, **kwargs):
        super(Event, self).__init__(*args, **kwargs)
        self.old_value_paid = self.paid

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.old_value_paid != self.paid and not self.paid:
            self.create_free_tariff()

    @property
    def lessons_elements(self):
        elements = []
        for unit in self.units.all_active():
            for lesson in unit.lessons.all_active():
                for element in lesson.elements.all_active():
                    elements.append(element)
        return elements

    def create_free_tariff(self):
        try:
            self.tariffications.all().delete()
        except Exception:
            raise Exception('Not was deleted tariffication! They is written in registres.')

        tariff = self.tariffications.create(
            title=f"Бесплатный тариф курса: {self.title}",
            paid=False,
            price=decimal.Decimal(0.00)
        )

        for lesson_element in self.lessons_elements:
            tariff.elements.create(lesson_element=lesson_element)

    def is_started(self, student):
        return self.records_execution.filter(student=student).exists()

    def is_finished(self, student):
        from billing.services import BillingService
        from payments.models import TarifficationElement

        count_avalaibe_elements = TarifficationElement.objects.filter(
            parent=BillingService.get_current_tariff(student, self),
            lesson_element__is_deleted=False,
            lesson_element__lesson__is_deleted=False,
            lesson_element__lesson__unit__is_deleted=False).distinct().count()

        count_completed_lesson_elements =\
            self.records_execution.filter(student=student).count()

        return count_avalaibe_elements == count_completed_lesson_elements


class EditorsEvent(models.Model):
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE,
        related_name='editors', verbose_name='Курс')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='editors_event', verbose_name='Пользователь')
    settings = models.BooleanField('Доступ к основным настройкам', default=False)
    tariffs = models.BooleanField('Доступ к тарифам', default=False)
    content = models.BooleanField('Доступ к содержимому', default=False)
    students = models.BooleanField('Доступ к студентам', default=False)
    homeworks = models.BooleanField('Доступ к домашним задания', default=False)
    date_create = models.DateTimeField('Дата создание записи',
                                       auto_now_add=True)
    date_update = models.DateTimeField('Дата обновление записи',
                                       auto_now=True)

    class Meta:
        unique_together = (('event', 'user'),)

second project/events/models/file_storages.py
from django.contrib.auth.models import User
from django.db import models



class FileStorage(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='file_storages',
        verbose_name='')
    file = models.FileField(
        upload_to='uploads', blank=True, null=True, verbose_name='Файл',
        max_length=255)
    url_third_party_res = models.URLField(
        'Ссылка на сторонний ресурс', max_length=255, blank=True, null=True)

second project/events/models/flows.py
from django.db import models

from .abstract_models import AbstractNotRemoveModel
from .events import Event


class Flow(AbstractNotRemoveModel):
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE,
        related_name='flows', verbose_name='Курс')
    title = models.CharField('Наименование',
                             max_length=250, blank=False,
                             null=False, default='Поток')
    date_begin = models.DateTimeField(
        'Дата начала', blank=True, null=True)
    is_enabled = models.BooleanField('Включенный', default=True)

    class Meta:
        verbose_name = 'Поток курса'
        verbose_name_plural = 'Потоки курсов'

second project/events/models/image_storages.py
from django.contrib.auth.models import User
from django.db import models

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class ImageStorage(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='image_storages',
        verbose_name='')
    image = models.ImageField(
        upload_to='uploads', blank=True, null=True, verbose_name='Изображение',
        max_length=255)
    cover = ImageSpecField(source='image',
                           processors=[ResizeToFill(640, 640)],
                           format='JPEG',
                           options={'quality': 80})

    @property
    def filename(self):
        return self.image.name

second project/events/models/signals.py
from django.db.models.signals import pre_save
from django.dispatch import receiver
from events.models import Lesson, LessonTest


@receiver(post_save, sender=Lesson)
def lesson_post_save(sender, **kwargs):
    LessonsTest.filter(lesson=sender).update(
        pass_count=sender.pass_count)

second project/events/templates/events/base_events.html
{% extends 'bootstrap/base.html' %}
{% load static %}

{% block content %}
  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div id="list_events" class="list-group list-group-flush">
        {%for item_event in events %}
            <a href="{% url 'events:event-detail' pk=item_event.pk%}" class="list-group-item list-group-item-action bg-light" style="{% if active_event == item_event %}background-color: #dae0e5!important;{% endif %}">{{item_event}}</a>
        {% endfor %}
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper" class="container">
        {% if user.is_authenticated %}
            <div class="btn-group" role="group">
                <a href="{%url 'events:home' %}?filter={{filter_events.0}}" class="btn btn-{% if active_filter == filter_events.0 %}primary{%else%}light{%endif%}">Все</a>
                {% if has_active_events_owner %}
                    <a href="{%url 'events:home' %}?filter={{filter_events.1}}" class="btn btn-{% if active_filter == filter_events.1 %}primary{%else%}light{%endif%}">Мои как владельца</a>
                {% endif %}
                {% if has_active_events_participant %}
                    <a href="{%url 'events:home' %}?filter={{filter_events.2}}" class="btn btn-{% if active_filter == filter_events.2 %}primary{%else%}light{%endif%}">Где я участвую</a>
                {% endif %}
            </div>
            <br>
        {% endif %}
        <br>
        {% block content_page %}
        {% endblock %}
    </div>
{% endblock %}

second project/events/templates/events/event_detail.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <h2>{{active_event}}</h2>
    <br>
    <div id="events">
            <table>
                <tbody>
                    {%for item in structure_units_lessons %}
                        <tr>
                            <td><a href="{% url 'events:detail-unit' event=active_event.pk pk=item.unit.pk %}">{{item.unit}}</a></td>
                            {% include 'partials/actions_table_row.html' with prefix_update=active_event.pk|slugify|add:'/units' prefix_remove='units' pk=item.unit.pk %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
    {% if active_event.owner == user %}
        <div style="margin-top:15px;">
            <a href="{% url 'events:create-unit' event=active_event.pk %}" class="btn btn-primary">Создать блок</a>
            <button type="button" class="btn btn-primary" onclick="everyoneInvolved()">Участвуют все</button>
        </div>
    {% endif %}
{% endblock %}

{% block jscustom %}
<script src="{% static 'admin/js/csrf.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    function everyoneInvolved(element){
        $.post("{% url 'events:add_all_user_to_event' event=active_event.pk %}", function(){
            swal.fire({
                "title": "",
                "text": "Успешно!",
                "type": "success",
                "confirmButtonClass": "btn btn-secondary"
            })
        })
        .fail(function(data){
            console.log(data);
            Swal.fire({
              icon: 'error',
              title: 'Произошла ошибка!',
              text: data.statusText,
              type: "error",
            })
        });
    }
</script>
{% endblock %}

second project/events/templates/events/event_list.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <a href="{% url 'events:create' %}" class="btn btn-primary">Создать курс</a>
    <h2>{{event}}</h2>    
    {% if lesson %}
        {{lesson}}
    {% endif %}
{% endblock %}

second project/events/templates/events/lesson_confirm_delete.html
{% extends 'events/object_confirm_delete.html' %}
{% block content_confirm %}Удалить урок: "{{object}}"?{% endblock %}

second project/events/templates/events/lesson_detail.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}


{% block content_page %}
    <h2>
    {{object.title}}
    </h2>
    
{% endblock %}

second project/events/templates/events/lesson_form.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}


{% block content_page %}
    <h2>
    {% if object.pk %}
        Редактирование урока
    {% else %}
        Создание нового урока
    {% endif %}
    </h2>
    <form  action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        {% if object.pk %}
            <a href="{% url 'events:remove-lesson' pk=object.pk %}" class="btn btn-secondary">Удалить</a>
        {% endif %}
    </form>
{% endblock %}

second project/events/templates/events/lesson_list.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <div class="modal-header">
        <a href="{% url 'events:create-lesson' %}" class="btn btn-primary"> Новый урок</a>
    </div>
    {%for lesson in lessons %}
        <a href="{% url 'events:update-lesson' pk=lesson.pk %}">{{lesson}}</a>
        <br>
    {% endfor %}
{% endblock %}

second project/events/templates/events/object_confirm_delete.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <form  action="" method="post">
        {% csrf_token %}
            {% block content_confirm %}{% endblock %}
            <div>
                <button type="submit" class="btn btn-primary">Удалить</button>
            </div>
    </form>
{% endblock %}

second project/events/templates/events/unit_detail.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <div class="modal-header">
    </div>
    <p>Уроки</p>
    <table>
        <tbody>
            {%for lesson in lessons %}
                        <tr>
                            <td><a href="{% url 'events:detail-lesson' event=active_event_pk unit=active_unit_pk pk=lesson.pk %}">{{lesson}}</a></td>
                            {% with prefix_update=active_unit_pk|slugify|add:'/lessons' prefix_remove='/events'|add:'/lessons' %}
                                {% include 'partials/actions_table_row.html' with prefix_update=prefix_update prefix_remove=prefix_remove pk=lesson.pk %}
                            {% endwith %}
                        </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if active_event.owner == user %}
        <a href="{% url 'events:create-lesson' event=active_event.pk unit=active_unit_pk %}" class="btn btn-primary">Создать урок</a>
    {% endif %}
    <p>Вебинары</p>
    <table>
        <tbody>
            {%for webinar in webinars %}
                        <tr>
                            <td><a href="{% url 'events:detail-webinar' event=active_event_pk unit=active_unit_pk pk=webinar.pk %}">{{webinar}}</a></td>
                            {% with prefix_update=active_unit_pk|slugify|add:'/webinars' prefix_remove='/events'|add:'/webinars' %}
                                {% include 'partials/actions_table_row.html' with prefix_update=prefix_update prefix_remove=prefix_remove pk=webinar.pk %}
                            {% endwith %}
                        </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if active_event.owner == user %}
        <a href="{% url 'events:create-webinar' event=active_event.pk unit=active_unit_pk %}" class="btn btn-primary">Создать вебинар</a>
    {% endif %}
{% endblock %}

second project/events/templates/events/unit_form.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <h2>
    {% if object.pk %}
        Редактирование блока
    {% else %}
        Создание нового блока
    {% endif %}
    </h2>
    
    <form  action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        {% if object.pk %}
            <a href="{% url 'events:remove-unit' pk=object.pk %}" class="btn btn-secondary">Удалить</a>
        {% endif %}
    </form>
{% endblock %}

second project/events/templates/events/webinar_confirm_delete.html
{% extends 'events/object_confirm_delete.html' %}
{% block content_confirm %}Удалить вебинар: "{{object}}"?{% endblock %}

second project/events/templates/events/webinar_list.html
{% extends 'events/base_events.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content_page %}
    <div class="modal-header">
        <a href="{% url 'events:create-webinar' %}" class="btn btn-primary"> Новый вебинар</a>
    </div>
    {%for webinar in webinars %}
        <a href="{% url 'events:update-webinar' pk=webinar.pk %}">{{webinar}}</a>
        <br>
    {% endfor %}
{% endblock %}